### ISSUE TITLE
Composable Profiles

### ISSUE THREAD

**Issue by MikeBirdTech** [OpenInterpreter/open-interpreter#1003]
### Is your feature request related to a problem? Please describe.

I have created two profiles for different models/api keys. One is for OpenAI and the other is for Azure.

When adding the `--os` flag, it executes this code:
```
    if args.os:
        args.profile = "os.py"
 ```
 
 This does not allow me to switch between credentials without re-writing `os.py` every time I want to switch.

### Describe the solution you'd like

When I run `OS Mode`, I would like to be able to choose which credentials are used. 

The command for this would be `interpreter -p profile1.yaml --os` and would use values from both files. Any conflicting fields would have `profile1.yaml` overwrite the values in `os.py`. I believe the only conflict would usually be `llm.model`

### Additional context

The `.py` profiles are more intimidating to edit than the `.yaml` profiles. Most users would only want to edit the yaml profiles so they should be able to control most configurations from there.

**Comment by lorenzejay** [comment]
I'd like to stake a stab at this
