### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by wu-clan** [OpenInterpreter/open-interpreter#1042]
### Describe the bug

```
  File "D:\Github\fastapi_chatgpt\.venv\lib\site-packages\interpreter\core\core.py", line 169, in _streaming_chat
    with open(
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\AppData\\Local\\Open Interpreter\\Open Interpreter\\conversations\\##_Plan\n\n1._Read_user__February_27_2024_18-57-36.json'
```

### Reproduce

interpreter.chat(message, stream=True) with ollama

### Expected behavior

response ok.

### Open Interpreter version

0.2.0

### Python version

3.10

### Operating System name and version

Windows 11

**Comment by MikeBirdTech** [comment]
Hi @wu-clan 
Are you able to update to the latest version of OI and try again?

The issue might be the filename of your conversation not being valid. If upgrading doesn't fix the issue, can you please rename the filepath to not have unique symbols like #? You can open the directory with `interpreter --conversations`

Thanks!
