### ISSUE TITLE
if message["type"] == "message": KeyError: 'type'

### ISSUE THREAD

**Issue by NatanAmado** [OpenInterpreter/open-interpreter#1045]
### Describe the bug

```
`
def load_chat_history(filename='chat_history.txt'):
    file_path = create_file_in_appdata(filename)
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return json.load(file)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        # Log errors rather than print them for production-ready code
        log_error("Loading chat history failed:", e)
        return []

def run_interpreter(userPrompt, api_key=None, interpreter_model='openai/gpt-4-vision-preview'):
    if api_key:
        Set_API_Key(api_key)
    try:
        # It would be better to manage the chat history state outside this function
        messages = load_chat_history()
        #interpreter.messages.extend(messages)
        #interpreter.system_message = read_prompt()
        interpreter.llm.context_window = 10000
        interpreter.llm.model = interpreter_model
        interpreter.llm.max_output = 2000
        interpreter.llm.max_tokens = 1000
        interpreter.auto_run = True
        interpreter.vision = True
        output = interpreter.chat(userPrompt, stream=True, display=False)
        for chunk in output:
            print(chunk, flush=True)

        interpreter.messages.extend(output)
        save_chat_history(interpreter.messages)
        
    except Exception as e:
        log_error(f"Error: {e}\n{traceback.format_exc()}")`

```
> Log Error: Error: 'type'
> Ignoring non-JSON content: Traceback (most recent call last):
> Ignoring non-JSON content:   File "/Users/n/Documents/Genesis/MauiApp2/bin/Debug/maccatalyst-x64/aimee.app/Contents/MonoBundle/../Resources/interpreter_wrapper.py", line 104, in run_interpreter
> Ignoring non-JSON content:     for chunk in output:
> Ignoring non-JSON content:   Fi
> Ignoring non-JSON content: le "/Users/n/anaconda3/lib/python3.11/site-packages/interpreter/core/core.py", line 148, in _streaming_chat
> Ignoring non-JSON content:     yield from self._respond_and_store()
> Ignoring non-JSON content:   File "/Users/n/anaconda3/lib/python3.11/site-packages/interpreter/core/core.py", line 194, in _respond_an
> Ignoring non-JSON content: d_store
> Ignoring non-JSON content:     for chunk in respond(self):
> Ignoring non-JSON content:   File "/Users/n/anaconda3/lib/python3.11/site-packages/interpreter/core/respond.py", line 49, in respond
> Ignoring non-JSON content:     for chunk in interpreter.llm.run(messages_for_llm):
> Ignoring non-JSON content:   File "/Users/n/anaconda3/lib/python3.11/site-package
> Ignoring non-JSON content: s/interpreter/core/llm/llm.py", line 94, in run
> Ignoring non-JSON content:     messages = convert_to_openai_messages(
> Ignoring non-JSON content:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Ignoring non-JSON content:   File "/Users/n/anaconda3/lib/python3.11/site-packages/interpreter/core/llm/utils/convert_to_openai_messages.py", line 23
> Ignoring non-JSON content: , in convert_to_openai_messages
> Ignoring non-JSON content:     if message["type"] == "message":
> Ignoring non-JSON content:        ~~~~~~~^^^^^^^^
> Ignoring non-JSON content: KeyError: 'type'
> 

### Reproduce

```
def load_chat_history(filename='chat_history.txt'):
    file_path = [FILEPATH_HERE]
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return json.load(file)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        # Log errors rather than print them for production-ready code
        log_error("Loading chat history failed:", e)
        return []

def run_interpreter(userPrompt, api_key=None, interpreter_model='openai/gpt-4-vision-preview'):
    if api_key:
        Set_API_Key(api_key)
    try:
        # It would be better to manage the chat history state outside this function
        messages = load_chat_history()
        #interpreter.messages.extend(messages)
        #interpreter.system_message = read_prompt()
        interpreter.llm.context_window = 10000
        interpreter.llm.model = interpreter_model
        interpreter.llm.max_output = 2000
        interpreter.llm.max_tokens = 1000
        interpreter.auto_run = True
        interpreter.vision = True
        output = interpreter.chat(userPrompt, stream=True, display=False)
        for chunk in output:
            print(chunk, flush=True)

        interpreter.messages.extend(output)
        save_chat_history(interpreter.messages)
        
    except Exception as e:
        log_error(f"Error: {e}\n{traceback.format_exc()}")`
        
```
      

Replace with the correct filepath that should lead to a .txt file with something like:

> [
>     {
>         "role": "user",
>         "type": "message",
>         "content": "No entry from user - please suggest something to enter."
>     },
>     {
>         "role": "assistant",
>         "type": "message",
>         "content": "**Plan:**\nI will provide the user with an option to either get emails or send emails using AppleScript on their Mac. If the user selects to get emails, I will execute the AppleScript command to retrieve the content of the last 3 emails from the Mail application. If the user chooses to send emails, I will prompt them to provide the necessary information to send an email using AppleScript."
>     }
> ]

### Expected behavior

Normal streamed response.

### Open Interpreter version

0.2.0

### Python version

Python 3.11.4

### Operating System name and version

MacOS 14.1.2 (23B92)

**Comment by piovis2023** [comment]
Any solutions to this error?

**Comment by Notnaton** [comment]
if message.get("type") == "message":
    # Do something
