### ISSUE TITLE
Issue during installation via terminal 

### ISSUE THREAD

**Issue by 855princekumar** [OpenInterpreter/open-interpreter#1098]
### Is your feature request related to a problem? Please describe.

Hello,

I wanted to share an issue I encountered while working with Python packages. I noticed that certain scripts installed via pip were inaccessible because their directory wasn't included in the system's PATH environment variable. This led to warning messages during package installation and usage. To address this, I've developed a simple batch script that updates the PATH variable, allowing seamless script execution from any location. I've documented this solution in a Git repository along with a README.md file. I believe implementing this script would significantly improve the user experience with Python packages. Your feedback on the repository would be invaluable.

![open interpreter issue](https://github.com/KillianLucas/open-interpreter/assets/68219958/1b3f3f0b-c828-4d6c-9ff5-981652caa753)

### Describe the solution you'd like

I've created a GitHub Gist repository where I've shared a simple batch script to address the issue of Python scripts not being in the PATH environment variable. This script resolves the warning messages that occur when installing or using Python packages by adding the specified directory containing Python scripts to the system's PATH. It's a straightforward solution aimed at improving the user experience with Python packages. You can find the script and instructions on how to use it in the repository. Feel free to check it out and provide any feedback or suggestions.

https://gist.github.com/855princekumar/505ee1c52a9aa2ba7439d7bda0287127

**Comment by Notnaton** [comment]
How did you install OI/python?
Seems like you have a custom installation of python

**Comment by 855princekumar** [comment]
not exactly, but previously I've installed Python as a work-on vs code so that might be the reason. but after this the interpreter works

**Comment by MikeBirdTech** [comment]
Another gist from @855princekumar that might help you out!

If you're experiencing PATH errors, you should check out the gist to see if it'll help.

Thanks @855princekumar!
