### ISSUE TITLE
Waiting for the model to load...

### ISSUE THREAD

**Issue by m1d232000** [OpenInterpreter/open-interpreter#1110]
### Describe the bug

Dear Developers,
I'm trying to use local phi-2.Q5_K_M.llamafile model, but it seems not to work in 0.2.3 (in 0.2.2 it works). It's stuck on step "Waiting for the model to load..." Please see on the attached screenshot.
Could you please fix it?
Thank you.

### Reproduce

cmd: interpreter --local

[?] What one would you like to use?:
 > Llamafile
   Ollama
   LM Studio
   Jan

Enter

[?] Select a Llamafile model to run or download a new one::
 > phi-2.Q5_K_M.llamafile
    ↓ Download new model

Enter

### Expected behavior

model loaded, ui starts

### Screenshots

![image](https://github.com/OpenInterpreter/open-interpreter/assets/66193682/e9b705cf-2720-4601-abea-d4206821a6d6)

### Open Interpreter version

0.2.3

### Python version

Python 3.11.7

### Operating System name and version

Windows 11

**Comment by m1d232000** [comment]
Hello,
I just have found it. It's because I have another server on 8080. So, it's needed to implement check here: https://github.com/OpenInterpreter/open-interpreter/blob/38a95aa9d30cdb0d72a637ddfedd7a20e8111cc5/interpreter/terminal_interface/profiles/defaults/local.py#L313
Have a good day, night or whatever.
Kind Regards,

**Comment by Notnaton** [comment]
Going to close this as it is solved.
@MikeBirdTech Should we add a --port flag for the llamafile or extract it from api_base?
