### ISSUE TITLE
Add information on how to view the docs

### ISSUE THREAD

**Issue by a-rbts** [OpenInterpreter/open-interpreter#1112]
### Is your feature request related to a problem? Please describe.

There seem to be extensive documentation in the doc repo, but those are under some specific format (mdx) that doesn't seem to be compatible with md viewers. I also tried the specific mdx extension for vscode, but this one complains on pretty much every file that some of the descriptor is missing, so I assume the docs need to be built somehow. 

### Describe the solution you'd like

I case of local use without Internet access, it would be useful to add pointers about how to build the documentation.

**Comment by MikeBirdTech** [comment]
I think this is a great idea @a-rbts 

Would you be interested in taking on this task? The docs are through [Mintlify](https://mintlify.com/docs/development)

The steps for launching the docs locally are
- `cd docs/`
- `mintlify dev`

**Comment by dheavy** [comment]
@MikeBirdTech, if @a-rbts doesn't take it in the next 24 hours, I'm willing to tackle this low-hanging fruit.
