### ISSUE TITLE
Display link to the Docs if error with flags 

### ISSUE THREAD

**Issue by Notnaton** [OpenInterpreter/open-interpreter#1113]
### Is your feature request related to a problem? Please describe.

when running:
´´´
interpreter --this-does-not-exist
```


### Describe the solution you'd like

when running:
´´´
interpreter --this-does-not-exist
```
Display the link to the docs

**Comment by Notnaton** [comment]
@MikeBirdTech

**Comment by Notnaton** [comment]
https://github.com/OpenInterpreter/open-interpreter/issues/1112

**Comment by benxu3** [comment]
Hi, I'd like to pick up this issue if no one else is currently working on it. Let me know if there's any additional information, licenses or agreements I have to provide. I didn't see anything on the CONTRIBUTING.md but I might've missed something obvious. Thanks!

**Comment by MikeBirdTech** [comment]
@benxu3 it's all yours!
Let us know if you need any help. Thank you so much for contributing!!

**Comment by benxu3** [comment]
Sorry for the delay with making a PR, busy wrapping up final assignments last week. Added the link to documentation in the error message. Please let me know any feedback you might have, especially regarding preferred formatting of the message. Thanks!
