### ISSUE TITLE
Colab Demo TypeError

### ISSUE THREAD

**Issue by bloomsa** [OpenInterpreter/open-interpreter#1119]
### Describe the bug

When trying to execute the [colab demo](https://colab.research.google.com/drive/1WKmRXZgsErej2xUriKzxrEAXdxMSgWbb?usp=sharing) in the readme, I'm getting the following error. I've ran through the `pip install` and runtime restart twice, both with the same outcome.

```python
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[/tmp/ipykernel_740/1305741230.py](https://localhost:8080/#) in <cell line: 1>()
----> 1 from interpreter import interpreter
      2 from google.colab import userdata
      3 
      4 # Paste your OpenAI API key below.
      5 interpreter.llm.api_key = userdata.get('openai')

7 frames

[/usr/lib/python3.10/importlib/util.py](https://localhost:8080/#) in __check_eager_loader(loader)
    273     def __check_eager_loader(loader):
    274         if not hasattr(loader, 'exec_module'):
--> 275             raise TypeError('loader must define exec_module()')
    276 
    277     @classmethod

TypeError: loader must define exec_module()
```

### Reproduce

1. open [colab demo in readme](https://colab.research.google.com/drive/1WKmRXZgsErej2xUriKzxrEAXdxMSgWbb?usp=sharing)
2. run cell 1 and restart session
3. run cell 2
4. TypeError on cell 2

### Expected behavior

I expected the import to be successful and to carry on with the demo notebook

### Open Interpreter version

0.2.3

### Python version

3.10.12

### Operating System name and version

Colab Free Tier

**Comment by huhusuzyzzz** [comment]
https://github.com/kubernetes/website/commit/82a57540364a69a6fcc3f7efc8c8b950bc020ce1

**Comment by huhusuzyzzz** [comment]
di.qq_1@icloud.com

**Comment by ben-kwh** [comment]
upvote, same issue

**Comment by An-Jhon** [comment]
upvote, same issue

**Comment by zachlewis** [comment]
Apparently, if you `! pip install opencv-python`, restart your runtime, and `import cv2` before `import interpreter`, things seem to work.

**Comment by 0xSMW** [comment]
> ###
> [Apr 3, 2024](#issuecomment-2034614028)

confirm this fix works

**Comment by sandeshrajbhandari** [comment]
> Apparently, if you `! pip install opencv-python`, restart your runtime, and `import cv2` before `import interpreter`, things seem to work.

this works for me too.
