### ISSUE TITLE
Connecting interpreter to hosted ollama server (LAN)

### ISSUE THREAD

**Issue by gibru** [OpenInterpreter/open-interpreter#1135]
### Is your feature request related to a problem? Please describe.

I'd like to connect to a server running ollama accessible over a static IP on LAN (e.g.192.168.77.10:11434)? I have configured ollama with its own static IP and confirmed that ollama is reachable.

So far I've tried the approach discussed in [running locally](https://docs.openinterpreter.com/guides/running-locally) as well as  the solution discussed [here](https://github.com/OpenInterpreter/01/issues/81).

Using `interpreter --model ollama/dolphin-mixtral:8x7b-v2.6`, is "ollama" refering to 127.0.0.1:11434? If so, can this be changed to point to ollama's to its static local IP address (e.g. 192.168.x.x)?

I've tried `--api_base 192.168.77.10:11434` but that sets the model to openai/gpt-4.

Any help/pointers in the right direction greatly appreciated.

### Describe the solution you'd like

Connecting `interpreter` to an ollama server hosted locally (static internal IP) so that interpreter and ollama don't have to be on the same device.

**Comment by Notnaton** [comment]
Add these flags:
```
--api_base http://host:port/v1
--model ollama/modelname
--api_key dummykey
```
Api key may or may not be necessary, openai api needs the key to be set to something.

**Comment by gibru** [comment]
> Add these flags:
> 
> ```
> --api_base http://host:port/v1
> --model ollama/modelname
> --api_key dummykey
> ```

Thanks a lot for helping out! I got it to work, however no **v1** after the port and I had to leave out the --api_key flag. This did the trick:

`interpreter --api_base http://host:port --model ollama/modelname`
