### ISSUE TITLE
Wrong version was uploaded to PyPi

### ISSUE THREAD

**Issue by Steve235lab** [OpenInterpreter/open-interpreter#1140]
### Describe the bug

~~I found that if build from the current main branch at [107a9e5](https://github.com/OpenInterpreter/open-interpreter/commit/107a9e5b5b96e8bfbfaa0fac4d80d4387f355444), the version will be `0.2.3` but with all new features added recently.~~ However, if install from PyPi with command `pip install open-interpreter`, the version will be `0.2.4`, but it misses the new features even with a higher version code. So I guess there's a mistake when uploading to PyPi.

### Reproduce

1. Clone the repo, and check out the main branch.
2. Build with command `pip install .`, now you have the latest nightly built version installed.
3. Check the version: `pip list | grep "open-interpreter"`, it will be `0.2.3`.
4. Test if it's updated with a new feature: `i -m gpt-4-turbo-preview`, chat something and see if there's a context window warning. If no warning shows, it means the current version installed is updated with latest updates. In my tests, there was no warning in this version.
5. Uninstall the one built from source: `pip uninstall open-interpreter`.
6. Install from PyPi: `pip install open-interpreter`.
7. Check the version: `pip list | grep "open-interpreter"`, it will be `0.2.4`.
8. Repeat the test in step 4, and you will see a warning, which means the version on PyPi misses the latest updates (including features mentioned in release change log) even it was tagged with a higher version code.

### Expected behavior

- [x] Tag version on PyPi with version code `0.2.4`.
- [ ] Update the package of version `0.2.4` on PyPi to include all new features and bug fixes mentioned in the release change log.
- [x] Make installations built from source on main branch always has a version code `>=` the latest one on PyPi to avoid upgrade warning messages showing in nightly built installations. It makes sense because our main branch should always be newer than PyPi.

### Open Interpreter version

0.2.4

### Python version

3.11.8

### Operating System name and version

Ubuntu 22.04.3 LTS & macOS Sonoma

### Additional context

@KillianLucas @Notnaton

**Comment by Steve235lab** [comment]
Oh, the version problem on main branch was solved in eeeee15fd6315e15306f5aa31494a7b0f4b25b91 just now. However, the PyPi version is still not right I think.

**Comment by Steve235lab** [comment]
Maybe we should use version code with different suffix to distinguish released versions and built from source versions like Cpython.

**Comment by MikeBirdTech** [comment]
Thanks for raising this Steve.

We're exploring git strategies to reduce confusion and improve reliability. I think we have a plan ready to implement but am open to hearing any suggestions you have. Thanks!
