### ISSUE TITLE
Moral when told not to be

### ISSUE THREAD

**Issue by LanceLake** [OpenInterpreter/open-interpreter#1143]
### Describe the bug

So I run an uncensored model in OobaBooga. I can get the program to talk to it, but when it does, it refuses to do immoral things (the general check I do for it is to ask it how to make meth). The model when using OobaBooga tells me. Open-Interpreter does not and says it can not do immoral things. 

### Reproduce

Connect OobaBooga to a non-filtered model. 
Ask it how to make meth and note that it answers.
Connect open-Interperter and ask it as well.
Note that it refuses even though the model connected and got the response from ooba. 

### Expected behavior

It does the immoral thing as the model told it to.

### Open Interpreter version

0.2.0

### Python version

3.11.5

### Operating System name and version

Windows 10

**Comment by MikeBirdTech** [comment]
Hi @LanceLake 
Sorry to hear that you have trouble with Open Interpreter not helping you make meth but this is out of scope for the project.

In all seriousness, when LLMs are given the power of code execution, guard rails are important. If you're looking for an uncensored chatbot, there are many alternatives available. You're also free to fork OI and manipulate the system message however you see fit. However, we will not be issuing a PR to enable meth production. Thanks

**Comment by LanceLake** [comment]
You DO realize the question is used as a test and not actually going to be followed. Right? I could've as easily asked it to any number of other illegal things. This doesn't mean I'm going to follow them.

Good to know though that this project agrees that censorship is the way to go. Makes it easier to find who not to follow rather than hem and haw around the subject. Thank you for saving me the trouble.

**Comment by Notnaton** [comment]
This is not censorship, we are making sure we don't execute code that can harm the system. 

You can simply modify the system message to enable meth production.
