### ISSUE TITLE
Always continuing

### ISSUE THREAD

**Issue by An-Jhon** [OpenInterpreter/open-interpreter#1146]
### Describe the bug

The proceedings seem to be continuing...When I execute the code `interpreter --model ollama/mistral`
![image](https://github.com/OpenInterpreter/open-interpreter/assets/44490800/ba48370f-c419-449f-929c-1820d898dbb3)

### Reproduce

interpreter --model ollama/mistral

### Expected behavior

Enter interaction

### Open Interpreter version

0.2.4

### Python version

3.9.0

### Operating System name and version

macOS13

**Comment by Notnaton** [comment]
Add the flags
```
--context_window 16000
--max_tokens 4000
```

**Comment by An-Jhon** [comment]
> Add the flags
> 
> ```
> --context_window 16000
> --max_tokens 4000
> ```

Thank you for your answer, and I try to rebooted the ollama, it works now
