### ISSUE TITLE
Error when inporting interpreter

### ISSUE THREAD

**Issue by lazymaniac** [OpenInterpreter/open-interpreter#1175]
### Describe the bug

I have the following error when I try to import interpreter:
```
Traceback (most recent call last):
  File "/home/seba/workspace/AutoProgrammer/interpreter.py", line 1, in <module>
    from interpreter import interpreter
  File "/home/seba/workspace/AutoProgrammer/interpreter.py", line 1, in <module>
    from interpreter import interpreter
ImportError: cannot import name 'interpreter' from partially initialized module 'interpreter' (most likely due to a circular import
```
I'm not python expert, but can't figure out what I did wrong. I installed open-interpreter with pip, pip in venv, conda but nothing helps. Other libs like crewai have no problem with imports.

### Reproduce

1. install open-interpreter
2. inport into .py file `from interpreter import interpreter`
3. run file

### Expected behavior

Import works

### Open Interpreter version

0.2.4

### Python version

3.11.8

### Operating System name and version

Fedora

### Additional context

Tested with open-interpreter `0.2.0` and `0.2.4`, python `3.10` and `3.11`

**Comment by imapersonman** [comment]
Thanks for using open-interpreter!  You're getting the error because your script is called `interpreter.py`.  In summary, the script you wrote is trying to import itself.  You can fix the issue by naming your script anything but `interpreter.py`.

Let us know if you run into any other issues!

**Comment by lazymaniac** [comment]
Yup, that was the problem. Thank you for explanation. I was looking everywhere except the right direction.
