### ISSUE TITLE
UserWarning: Field "model_id" has conflict with protected namespace "model_"  - pydantic

### ISSUE THREAD

**Issue by datametal** [OpenInterpreter/open-interpreter#1176]
### Describe the bug

On starting interpreter: 

' ' ' BEGIN ERROR: 

❯ interpreter
/home/$USER/.local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected nam
espace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

▌ Model set to gpt-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

>
' ' ' END 

Arch Linux | python 3.11.8  | installed OI via pip with --break-system-packages flag 
Seems to be non-blocking / pydantic being extra persnickety ?  thanks 

### Reproduce

1. install oi via pip install oi --break-system-packages 
2. run interpreter 
3. see error (or warning, non-blocking error)

### Expected behavior

open interpreter runs without warning 

### Open Interpreter version

0.2.4

### Python version

3.11.8 

### Operating System name and version

Arch Linux 6.8.2

**Comment by stefandamyanov** [comment]
I have the exact same issue when I install with any of the below commands: 

curl -o oi-linux-installer.sh https://raw.githubusercontent.com/KillianLucas/open-interpreter/main/installers/oi-linux-installer.sh && chmod +x oi-linux-installer.sh && ./oi-linux-installer.sh && rm oi-linux-installer.sh

pip install open-interpreter

**Comment by omani** [comment]
this seems to be something that happened recently. I am affected as well.

**Comment by datametal** [comment]
Possible that simply changing "model_id" to "model_id_local" in https://github.com/OpenInterpreter/open-interpreter/blob/main/interpreter/core/llm/vision_for_text_llms.py would resolve the issue? I haven't read through the contributor docs yet to open a PR. If someone wants to try, go ahead please.  thank you.

**Comment by teereximus88** [comment]
Getting the same issue here as well...

<img width="1115" alt="Screenshot 2024-04-06 at 1 09 17 AM" src="https://github.com/OpenInterpreter/open-interpreter/assets/79544431/79d3821e-dd82-499a-b129-670c45883cf2">

**Comment by rmangino** [comment]
Clean install of macOS 14.4.1 and Anaconda. I'm seeing similar output to everyone else. I can't just ignore the warnings as open-interpreter does not return any results (I've tried my OpenAI key and Anthropic key).

[screenshot](https://imgur.com/Sdf4A2H)

**Comment by imapersonman** [comment]
The warnings are being printed inside of an LiteLLM import, particularly [this](https://github.com/OpenInterpreter/open-interpreter/blob/dbcc9e83c189a3721c109b713571567def4c700a/interpreter/terminal_interface/utils/count_tokens.py#L3) one.  I wrote a gist describing the problem [here](https://gist.github.com/imapersonman/39d0c4a315090a0c02d2921fa0ae6ed8).  I'm currently writing a PR to fix the issue that should be up later tonight.

**Comment by rob317** [comment]
/opt/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

**Last attempt Apr 8** Macos 14.4.1 - Python 3.11.7 + Anaconda 
**I have previously tried** pyenv + 3.11.7 with same result
**Tried** Brew.sh + 3.10 / Brew.sh + 3.11 / Brew.sh + 3.11.7 with same result
**Have initially tried on Apr 4** "curl -o oi-mac-installer.sh https://raw.githubusercontent.com/KillianLucas/open-interpreter/main/installers/oi-mac-installer.sh && chmod +x oi-mac-installer.sh && ./oi-mac-installer.sh && rm oi-mac-installer.sh" - same results

Thank you
