### ISSUE TITLE
Crashes with gpt-4-turbo-2024-04-09

### ISSUE THREAD

**Issue by kinopeee** [OpenInterpreter/open-interpreter#1190]
### Describe the bug

When I run the program with gpt-4-turbo-2024-04-09, it generates a dump and then crashes.

### Reproduce

1. launch interpreter with gpt-4-turbo-2024-04-09.
2. Have interpreter write and execute a program.

### Expected behavior

no error and no clash.

### Screenshots

![e1](https://github.com/OpenInterpreter/open-interpreter/assets/119112484/88bf7b08-e370-48fa-9c39-d494cde3533c)
![e2](https://github.com/OpenInterpreter/open-interpreter/assets/119112484/69a49a3f-94b5-49aa-8640-427740bf6aca)
![e3](https://github.com/OpenInterpreter/open-interpreter/assets/119112484/782fdfc8-7c43-4efd-981a-e0a5af6d2a17)

### Open Interpreter version

0.2.4 New Computer Update

### Python version

3.10.4

### Operating System name and version

macOS 14.4.1

**Comment by emec2023** [comment]
The new Turbo model is working fine in my system

**Comment by MikeBirdTech** [comment]
This PR bumps the LiteLLM version and I believe it will resolve the issue
https://github.com/OpenInterpreter/open-interpreter/pull/1195

Stay tuned!

**Comment by kinopeee** [comment]
I've confirmed this issue has been resolved. Thanks! @MikeBirdTech
