### ISSUE TITLE
OpenAPI token balance

### ISSUE THREAD

**Issue by emec2023** [OpenInterpreter/open-interpreter#1191]
### Describe the bug

Its not necessary a bug but the balance for Chatgpt 4 reduces very drastically. I tried reducing the max output tokens but with in minutes the balance reduced by 0.5 dollars. I am just trying to run few python codes and perform data analysis. But if the balance burns at such a high rate it will be not possible to use ChatGPT4 in the open interpreter. But its very promising specially working with large dataset and libraries that are not available with ChatGPT Plus.

### Reproduce

Run python code with error messages

### Expected behavior

I was hoping the balance for openai will reduce at a lower rate

### Open Interpreter version

0.1.1

### Python version

3.10

### Operating System name and version

windows 11

**Comment by CyanideByte** [comment]
If you add this parameter, the price will be reduced to about a third.
`--model gpt-4-turbo-preview`

**Comment by MikeBirdTech** [comment]
Yes, to reduce cost please select another model
