### ISSUE TITLE
Getting 429 Error code when giving valid Open AI Key

### ISSUE THREAD

**Issue by GSrinivasKishanLal** [OpenInterpreter/open-interpreter#1197]
### Describe the bug

When trying to run the interpreter command in windows prompt, getting below error always even also when giving a valid Open AI key with GPT 4.0 availability:

 OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Kindly suggest on a solution to fix it.

### Reproduce

1) After giving Open AI API key and press enter, in prompt get message to use GPT 3.5 instead of GPT 4.0
2) After giving Yes, get issue stating 429 ERROR code as not quotas.

### Expected behavior

Some valid response from interpreter

### Open Interpreter version

0.2.4

### Python version

3.10.6

### Operating System name and version

windows

**Comment by MikeBirdTech** [comment]
The OpenAI docs say
```
Cause: You have run out of credits or hit your maximum monthly spend.
Solution: [Buy more credits](https://platform.openai.com/account/billing) or learn how to [increase your limits](https://platform.openai.com/account/limits).
```
Have you tried this?
Have you tried the API key via curl?

**Comment by GSrinivasKishanLal** [comment]
> The OpenAI docs say
> 
> ```
> Cause: You have run out of credits or hit your maximum monthly spend.
> Solution: [Buy more credits](https://platform.openai.com/account/billing) or learn how to [increase your limits](https://platform.openai.com/account/limits).
> ```
> 
> Have you tried this? Have you tried the API key via curl?

Thank you for your suggestion, I have not tried API key via curl.
