### ISSUE TITLE
gpt-4 to gpt-3.5 turbo llm change

### ISSUE THREAD

**Issue by philiphusseinn** [OpenInterpreter/open-interpreter#1207]
How can I change the llm that the open interpreter 01 is connecting with? As I've understood by default it's GPT 4 which is very expensive to use as API. How can I change it to GPT 3.5 Turbo which is ten times cheaper?

**Comment by MikeBirdTech** [comment]
Please raise issues regarding the 01 in the proper repository: https://github.com/OpenInterpreter/01

To change the model for Open Interpreter, here are the docs: https://docs.openinterpreter.com/language-models/hosted-models/openai

Thanks!
