### ISSUE TITLE
ollama llama3 How to remove the first line " ` " when generating code in Windows 11 terminal

### ISSUE THREAD

**Issue by ltsyk** [OpenInterpreter/open-interpreter#1228]
### Describe the bug

ollama llama3 "`" symbols frequently appear in the first line when generating code in Windows 11 terminal

### Reproduce

ollama llama3 "`" symbols frequently appear in the first line when generating code in Windows 11 terminal

### Expected behavior

ollama llama3 When generating code in Windows 11 terminal, the "`" symbol should not appear in the first line

### Screenshots

![Uploading 屏幕截图 2024-04-23 212337.png…]()

### Open Interpreter version

0.2.4

### Python version

3.11.9

### Operating System name and version

windows11

### Additional context

open interpreter This error occurs when running ollama llama3

**Comment by Therealkorris** [comment]
gh pr checkout 1217

thanks to the author

**Comment by HoodBlah** [comment]
How did you fix it? Is there something I can do on my client to get it to work?
