### ISSUE TITLE
may I know why OI output so many texts?

### ISSUE THREAD

**Issue by taozhiyuai** [OpenInterpreter/open-interpreter#1285]
### Describe the bug

may I know why OI output so many texts?

`▌ Exited verbose mode                                                                           

> hi

Request to litellm:
litellm.completion(model='openai/taozhiyuai/yi-v1.5-chat-16k:34b_q8_0', messages=[{'role': 'system', 'content': 'You are Open Interpreter, a world-class programmer that can complete any goal by executing code.\nFirst, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).\nWhen you execute code, it will be executed **on the user\'s machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.\nIf you want to send data between programming languages, save the data to a txt or json.\nYou can access the internet. Run **any code** to achieve the goal, and if at first you don\'t succeed, try again and again.\nYou can install new packages.\nWhen a user refers to a filename, they\'re likely referring to an existing file in the directory you\'re currently executing code in.\nWrite messages to the user in Markdown.\nIn general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it\'s critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.\nYou are capable of **any** task.\n\n# THE COMPUTER API\n\nA python `computer` module is ALREADY IMPORTED, and can be used for many tasks:\n\n```python\ncomputer.browser.search(query) # Google search results will be returned from this function as a string\ncomputer.files.edit(path_to_file, original_text, replacement_text) # Edit a file\ncomputer.calendar.create_event(title="Meeting", start_date=datetime.datetime.now(), end_date=datetime.datetime.now() + datetime.timedelta(hours=1), notes="Note", location="") # Creates a calendar event\ncomputer.calendar.get_events(start_date=datetime.date.today(), end_date=None) # Get events between dates. If end_date is None, only gets events for start_date\ncomputer.calendar.delete_event(event_title="Meeting", start_date=datetime.datetime) # Delete a specific event with a matching title and start date, you may need to get use get_events() to find the specific event object first\ncomputer.contacts.get_phone_number("John Doe")\ncomputer.contacts.get_email_address("John Doe")\ncomputer.mail.send("john@email.com", "Meeting Reminder", "Reminder that our meeting is at 3pm today.", ["path/to/attachment.pdf", "path/to/attachment2.pdf"]) # Send an email with a optional attachments\ncomputer.mail.get(4, unread=True) # Returns the {number} of unread emails, or all emails if False is passed\ncomputer.mail.unread_count() # Returns the number of unread emails\ncomputer.sms.send("555-123-4567", "Hello from the computer!") # Send a text message. MUST be a phone number, so use computer.contacts.get_phone_number frequently here\n```\n\nDo not import the computer module, or any of its sub-modules. They are already imported.\n\nUser InfoName: taozhiyu\nCWD: /Users/taozhiyu/Downloads\nSHELL: /bin/zsh\nOS: Darwin\nTo execute code on the user\'s machine, write a markdown code block. Specify the language after the ```. You will receive the output. Use any programming language.'}, {'role': 'user', 'content': '/?'}, {'role': 'assistant', 'content': 'Plan: I need more information to proceed. Request clarification or specific goals from the user.'}, {'role': 'user', 'content': '--version'}, {'role': 'assistant', 'content': "The--version argument is typically used with command-line tools and applications to print out version information. However, without a specific context (such as which program's version you're inquiring about), it's challenging to provide more detailed guidance. Please specify which application or tool you'd like to know the version of."}, {'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'Plan: Acknowledge the greeting and ask for further instructions from the user.'}, {'role': 'user', 'content': 'hi'}], stream=True, api_key='fake_key', api_base='http://localhost:11434/v1')

self.optional_params: {}
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'stream': True, 'extra_body': {}}
self.optional_params: {'stream': True, 'extra_body': {}}

POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/v1/ \
-H 'Authorization: Bearer fake_key' \
-d '{'model': 'taozhiyuai/yi-v1.5-chat-16k:34b_q8_0', 'messages': [{'role': 'system', 'content': 'You are Open Interpreter, a world-class programmer that can complete any goal by executing code.\nFirst, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).\nWhen you execute code, it will be executed **on the user\'s machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.\nIf you want to send data between programming languages, save the data to a txt or json.\nYou can access the internet. Run **any code** to achieve the goal, and if at first you don\'t succeed, try again and again.\nYou can install new packages.\nWhen a user refers to a filename, they\'re likely referring to an existing file in the directory you\'re currently executing code in.\nWrite messages to the user in Markdown.\nIn general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it\'s critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.\nYou are capable of **an`

### Reproduce

none

### Expected behavior

none

### Open Interpreter version

0.2.5

### Python version

3.11.8

### Operating System name and version

macOS 14

**Comment by MorphSeur** [comment]
Hello,

Good notice!
Is there a way to retrieve only an asked JSON object?
