### ISSUE TITLE
How to set Custom API?

### ISSUE THREAD

**Issue by drakewxh** [OpenInterpreter/open-interpreter#1367]
### Describe the bug

My local API is "http://0.0.0.0:7009/v1/chat/completions". According to the link below:
https://docs.openinterpreter.com/settings/all-settings#api-base
I excuted the command"interpreter --api_base 'http://0.0.0.0:7009/v1/chat/completions'"
But the Model was set to openai/gpt-4-turbo, how can i use my cunstom API?

### Reproduce

I excuted the command"interpreter --api_base 'http://0.0.0.0:7009/v1/chat/completions'"
But the Model was set to openai/gpt-4-turbo
▌ Model set to openai/gpt-4-turbo

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

### Expected behavior

I should use my custom api by using "interpreter --api_base xxx"

### Open Interpreter version

Open Interpreter 0.3.4 Local III

### Python version

3.11.0

### Operating System name and version

Linux

**Comment by Notnaton** [comment]
--api_base http://localhost:port/v1

**Comment by drakewxh** [comment]
> --api_base http://localhost:port/v1

Thanks a lot!!!
