### ISSUE TITLE
Misleading error messages when users enter invalid Groq model

### ISSUE THREAD

**Issue by MikeBirdTech** [OpenInterpreter/open-interpreter#1368]
### Describe the bug

This occurs when trying to use one of the new Groq models, such as `llama-3.1-405b-reasoning` and non-paying users do not have access. This might occur with other invalid models as well, but I haven't tested.

When the user runs `interpreter --model groq/llama-3.1-405b-reasoning --api_base https://api.groq.com/openai/v1 --api_key $GROQ_API_KEY` 
the error is
```
  You do not have access to openai/groq/llama-3.1-405b-reasoning. You will need to add a payment method and purchase credits for the OpenAI API billing page (different from ChatGPT) to use `GPT-4`.

.com/account/billing/overview

Would you like to try GPT-3.5-TURBO instead? (y/n)
```

### Reproduce

Run `interpreter --model groq/llama-3.1-405b-reasoning --api_base https://api.groq.com/openai/v1 --api_key $GROQ_API_KEY` 

Enter any prompt

### Expected behavior

An error message that is related to the provider of the model attempted to be used

### Open Interpreter version

0.3.4

### Python version

3.11.7

### Operating System name and version

MacOS

**Comment by ighoshsubho** [comment]
I want to fix this, can you assign me please.

**Comment by MikeBirdTech** [comment]
@ighoshsubho It's all yours! Looking forward to the PR
