### ISSUE TITLE
run OI with OLLAMA SERVER IN NETWORK

### ISSUE THREAD

**Issue by RM-S2** [OpenInterpreter/open-interpreter#1384]
### Describe the bug

i try to run OI with ollama server in another server computer in my network.and the command start OI is:
interpreter --model  ollama/llama3.1 --api_base "http://192.168.3.13:11434" --api_key "fake_key"
but i get error say cant fine ollama in my computer ,what i thought is wrong because  OI shoud find ollama in my server computer.
what should i do ?

### Reproduce

interpreter --model  ollama/llama3.1 --api_base "http://192.168.3.13:11434" --api_key "fake_key"

### Expected behavior

interpreter --model  ollama/llama3.1 --api_base "http://192.168.3.13:11434" --api_key "fake_key"

### Open Interpreter version

0.3.4

### Python version

3.1.14

### Operating System name and version

win11

**Comment by CyanideByte** [comment]
This was probably fixed by this: https://github.com/OpenInterpreter/open-interpreter/pull/1387

**Comment by RM-S2** [comment]
> This was probably fixed by this: #1387

thanks~!
