### ISSUE TITLE
Where are chat logs saved?

### ISSUE THREAD

**Issue by bitcoinmeetups** [OpenInterpreter/open-interpreter#1414]
### Describe the bug

Where are chat logs saved?

### Reproduce

No chat logs

### Expected behavior

Expecting chat logs

### Open Interpreter version

latest

### Python version

latest

### Operating System name and version

linux emulators

**Comment by MikeBirdTech** [comment]
Open the terminal and enter the command 
`interpreter --conversations` and then select `Open Folder`
