### ISSUE TITLE
Can I connect open interpreter to a running llamafile?

### ISSUE THREAD

**Issue by bitcoinmeetups** [OpenInterpreter/open-interpreter#1420]
### Is your feature request related to a problem? Please describe.

Can I connect open interpreter to a running llamafile?

If so, how?
If not = feature request.

### Describe the solution you'd like

Some easy solution to connect open interpreter to a llamafile

**Comment by MikeBirdTech** [comment]
Yes, please check the docs
https://docs.openinterpreter.com/guides/running-locally
