### ISSUE TITLE
How to use with gemini api key

### ISSUE THREAD

**Issue by hyroxtvvv** [OpenInterpreter/open-interpreter#1453]
### Describe the solution you'd like

How can I use the api key in https://aistudio.google.com/

**Comment by MikeBirdTech** [comment]
Follow the instructions here: https://docs.litellm.ai/docs/providers/gemini

**Comment by 6rz6** [comment]
interpreter -m gemini-1.5-flash -ab https://generativelanguage.googleapis.com -ak YOUR_API_KEY

📠 [Google inference API Docs](https://ai.google.dev/api/all-methods)

**Comment by kadavilrahul** [comment]
I am not able to use it. Has anyone done it? I am using API from Google AI studio.
