### ISSUE TITLE
OS mode can't execute code (win 11)

### ISSUE THREAD

**Issue by superafu** [OpenInterpreter/open-interpreter#1460]
### Describe the bug

When run OS mode in win 11, it can generate plans and code properly, but can't execute the code. Does anyone have the same issue? Non OS mode works pretty fine with code executed.

### Reproduce

1. interpreter --model "deepseek-coder" --api_base "https://api.deepseek.com" --api_key "xxx" --os
2.  OS Control enabled. Warning: In this mode, Open Interpreter will not require approval before performing actions. Be ready to close your
terminal.
3. Quest: open my C drive folder. Reply:   "To open your C: drive folder, we can use a simple PowerShell command to start a new File Explorer window at the root
  of the C: drive. Let's execute the following code:
   Start-Process C:\
  This command will open a new File Explorer window at the root of the C: drive.

  Let's execute this command and verify the result.

   import time
..... Then succesful." But the folder was never opened up.

### Expected behavior

Expecting code can be executed.

### Open Interpreter version

0.3.13 

### Python version

3.10

### Operating System name and version

win 11

**Comment by MikeBirdTech** [comment]
Currently, OS mode only supports Claude computer use. We're working towards figuring out a way to support more.
