### ISSUE TITLE
Possible bug: only the last message is recognized by the assistant when sending to /openai/chat/completions

### ISSUE THREAD

**Issue by PatrickNercessian** [OpenInterpreter/open-interpreter#1462]
### Describe the bug

https://github.com/OpenInterpreter/open-interpreter/blob/c81d910164f5e7a09d4fdd131e6fbde3d4b7f4d2/interpreter/core/async_core.py#L789-L803

Not sure if this is intentional or not, but doesn't seem like it to me?

### Reproduce

Send a message like

```
url = "http://localhost:8000/openai/chat/completions"
headers = {"Content-Type": "application/json"}
data = {"auth": "dummy-api-key", "messages": [{"role": "user", "content": "Hello! Can you use python to generate 93 raised to the 4th power"}, {"role": "user", "content": "What was the last message I sent, if any?"}]}
response = requests.post(url, headers=headers, data=json.dumps(data))

data = {"auth": "dummy-api-key", "messages": [{"role": "user", "content": "{START}"}]}
response = requests.post(url, headers=headers, data=json.dumps(data))
print(response.json())
```

### Expected behavior

Multiple messages to be sent and received

### Open Interpreter version

0.3.10

### Python version

python:3.11.8

### Operating System name and version

Debian

**Comment by MikeBirdTech** [comment]
Hey @PatrickNercessian 
I'm not able to reproduce this. Can you give a more detailed explanation how you got to this point?
Thanks!

**Comment by PatrickNercessian** [comment]
Hey, thanks for following up. I think maybe it is actually intentional? I am not sure.

But the code in `reproduce` should reproduce it. I am running OpenInterpreter by building the Docker image and running the server that way. Then running the `reproduce` code locally, outside the container.

But you can even tell from the linked code block, it only grabs the last message 

This no longer affects me because I built my own server code for using OpenInterpreter, so feel free to close or leave this open!
