### ISSUE TITLE
Expired discord links in readmes

### ISSUE THREAD

**Issue by aaronrmm** [OpenInterpreter/open-interpreter#1491]
### Describe the bug

The discord invites have expired. For example, in [docs/CONTRIBUTING.md](https://github.com/OpenInterpreter/open-interpreter/blob/main/docs/CONTRIBUTING.md) the link https://discord.gg/6p3fD6rBVm has expired.

### Reproduce

Try clicking here: https://discord.gg/6p3fD6rBVm
And here: https://discord.gg/Hvz9Axh84z
Do a search for "discord.gg" in this repo and you will find only these links.

### Expected behavior

Discord opens and ask me if I'd like to join.

### Screenshots

![Screenshot 2024-10-23 064329](https://github.com/user-attachments/assets/7ea02dd9-c01e-4c7e-915f-70d214d52e04)

### Open Interpreter version

v0.3.14, also main and develop. All branches as far as I could tell.

### Python version

N/A

### Operating System name and version

N/A

### Additional context

I'd love to join your fantastic project! Thank you!

**Comment by bobemoe** [comment]
Hmm, I just tried those invite links and they worked for me!

**Comment by aaronrmm** [comment]
Hmm. I had issues in two browsers (edge and firefox), but it worked through discord. Sorry about that!
