### ISSUE TITLE
Computer use bugs

### ISSUE THREAD

**Issue by austinmw** [OpenInterpreter/open-interpreter#1501]
### Describe the bug

I've faced two bugs with computer use:

1. Not authorized error

```
I'll help you open Spotify using Spotlight. I'll press Command+Space, type "Spotify", and press Return.

{"action": "key", "text": "command+space"}{"action": "type", "text": "spotify"}{"action": "key", "text": "Return"}{"action": "screenshot"}56:119: execution error: Not authorized to send Apple events to System Events. (-1743)
```

2. Screen resolution error: Using a retina MBP M2 16" the mouse clicks do not seem to move to the correct screen locations.

### Reproduce

`interpreter --os`

### Expected behavior

Authorize use and click correctly

### Open Interpreter version

0.4.2

### Python version

3.12

### Operating System name and version

Mac 15.0.1

**Comment by MikeBirdTech** [comment]
The auth error is related to your terminal, check out `System Preferences > Security & Privacy` but I'm not sure which specific permission needs to be granted.
