### ISSUE TITLE
[Request] Claude Computer use Python example

### ISSUE THREAD

**Issue by austinmw** [OpenInterpreter/open-interpreter#1511]
### Is your feature request related to a problem? Please describe.

I don't currently see any examples for computer use with claude outside of the CLI

### Describe the solution you'd like

Python Jupyter notebook example of interacting with Claude Computer use, and it successfully taking screenshots, controlling mouse and keyboard, etc.

**Comment by MikeBirdTech** [comment]
OS mode is not currently available in Python

https://docs.openinterpreter.com/settings/all-settings#os-mode
