### ISSUE TITLE
how do you automate the execution of the code? 

### ISSUE THREAD

**Issue by kyegomez** [OpenInterpreter/open-interpreter#1519]
### Describe the bug

how do you automate the execution of the code? Need the setting to automate it so the code will auto execute.

### Reproduce

how do you automate the execution of the code? Need the setting to automate it so the code will auto execute.

### Expected behavior

how do you automate the execution of the code? Need the setting to automate it so the code will auto execute.

### Open Interpreter version

0.1.1

### Python version

3.115

### Operating System name and version

Macos

### Additional context

how do you automate the execution of the code? Need the setting to automate it so the code will auto execute.

**Comment by MikeBirdTech** [comment]
Two options:

https://docs.openinterpreter.com/settings/all-settings#auto-run

or

<img width="513" alt="image" src="https://github.com/user-attachments/assets/7880da2b-9c1b-4530-8ba8-d3b6b18722bd">

There's also the `-y` flag when you run Open Interpreter in the CLI
