### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by mak448a** [OpenInterpreter/open-interpreter#152]
Please write a warning message for when you are using GPT4 so that the users know that their [username is being sent to GPT4](https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/interpreter.py#L118). This program also sends your operating system, and your working directory. It's fine by me if you send it to a local AI, but please inform the users when you are sending to OpenAI's servers.

Thank you,
mak448a

Source code:
https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/interpreter.py#L118
https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/interpreter.py#L363

**Comment by mtin79** [comment]
Hi @mak448a , thanks for bringing this up.
I would love a bit more information on the implications on using OPENAI's models like GPT-4 / 3.5 ... has on the information being processed!

- Are only the instructions send to OPENAI or also the documents one works with?  
- Where is privacy and confidential information exchanged?  
- More documentation about where information leaks and how running open interpreter locally makes it different.  

Thanks @KillianLucas or any other contributer for commeting ...

**Comment by mak448a** [comment]
> Hi @mak448a , thanks for bringing this up. I would love a bit more information on the implications on using OPENAI's models like GPT-4 / 3.5 ... has on the information being processed!
> 
>     * Are only the instructions send to OPENAI or also the documents one works with?
> 
>     * Where is privacy and confidential information exchanged?
> 
>     * More documentation about where information leaks and how running open interpreter locally makes it different.
> 
> 
> Thanks @KillianLucas or any other contributer for commeting ...

Well, it sends the directory names and file names to OpenAI, but the actual contents are not, as far as I know.

**Comment by mak448a** [comment]
If you're seeing in your email, I've edited the above message which had false information. Please read the most up to date version on GitHub. Thanks :)

**Comment by medvedev1088** [comment]
Another privacy concern is it sends your messages to https://open-procedures.replit.app/

https://github.com/KillianLucas/open-interpreter/blob/c71078027fb6331adf9080c337802af73654c28d/interpreter/interpreter.py#L158

**Comment by cheestudio** [comment]
Bummer. This is going to be the main reason I can't leverage this tool, but I understand why it kind of has to be this way to function properly and in a way that's helpful.

**Comment by mak448a** [comment]
> Bummer. This is going to be the main reason I can't leverage this tool, but I understand why it kind of has to be this way to function properly and in a way that's helpful.

If you want to use it, you can still use it offline locally

**Comment by cheestudio** [comment]
@mak448a Ah but if I do that, I'd need a local model like falcon or llama running, as well, correct?

**Comment by mak448a** [comment]
Yes

**Comment by mak448a** [comment]
> Another privacy concern: it sends messages to https://open-procedures.replit.app/
> 
> https://github.com/KillianLucas/open-interpreter/blob/c71078027fb6331adf9080c337802af73654c28d/interpreter/interpreter.py#L158

Update: Apparently it doesn't use this anymore.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if privacy concerns have not been addressed. Thanks!

**Comment by mak448a** [comment]
Could you re open this issue @MikeBirdTech? https://github.com/KillianLucas/open-interpreter/blob/main/docs/legal/privacy-policy.mdx is still not filled out.

**Comment by MikeBirdTech** [comment]
Hi @mak448a 
Thanks for pointing that out.

There is a privacy policy here: 
https://github.com/KillianLucas/open-interpreter/blob/6d1238412bee1074d41a9499ca0fbaf12cb7a3c9/docs/legal/license.mdx

Which can be found online:
https://docs.openinterpreter.com/legal/license

I will have the team review it to ensure it's up to date and then update the docs to match.
