### ISSUE TITLE
Change formatter from Black to Ruff

### ISSUE THREAD

**Issue by MikeBirdTech** [OpenInterpreter/open-interpreter#849]
### Describe the solution you'd like

Changing from Black to Ruff will increase the speed of development and deployment. From [Astral](https://astral.sh/):
`The Ruff formatter is an extremely fast Python formatter, written in Rust. It’s over 30x faster than [Black](https://github.com/psf/black) and 100x faster than [YAPF](https://github.com/google/yapf), formatting large-scale Python projects in milliseconds — all while achieving >99.9% Black compatibility.`

More information can be found on their [blog post](https://astral.sh/blog/the-ruff-formatter)

### Additional context

Lots of projects are switching to Ruff and seeing massive performance gains. Some examples are: Gradio, Jax, Flask, and [many more](https://x.com/charliermarsh)

**Comment by KillianLucas** [comment]
I think this is smart for attracting the Rust community :) Will merge Suibhne's PR and close this!
