### ISSUE TITLE
'interpreter' is not recognized as an internal or external command (win11)

### ISSUE THREAD

**Issue by chenqiJV** [OpenInterpreter/open-interpreter#897]
### Describe the bug

while I install interpreter with 'pip install open-interpreter' , it seems succeed . But When I run the interpreter, the terminal displays 'interpreter' is not recognized as an internal or external command, operable program, or batch file.

### Reproduce

1.pip install open-interpreter
2.interpreter

then : 
'interpreter' is not recognized as an internal or external command, operable program, or batch file.

### Expected behavior

begin interactive chat

### Open Interpreter version

latest

### Python version

3.10.5

### Operating System name and version

win11

**Comment by filip-van-hoeckel** [comment]
+1

**Comment by Notnaton** [comment]
Try this:
```
pip install --force-reinstall open-interpreter
```

**Comment by filip-van-hoeckel** [comment]
Solved it, but make sure you're an elevated user when doing so. After that Interpreter can run with regular user privileges.
