### ISSUE TITLE
Unable to edit config files after upgrade to 0.2.0

### ISSUE THREAD

**Issue by MatiasBarboza** [OpenInterpreter/open-interpreter#910]
### Describe the bug

I am getting this error when trying to edit the config file:

mati@pop-os-de-mati:~$ interpreter --config
Opening `/home/mati/.config/Open Interpreter/config.yaml`...
[     0.003] W: QObject::moveToThread: Current thread (0x64dc5aa3b510) is not the object's thread (0x64dc5aa503f0).
Cannot move to target thread (0x64dc5aa3b510)

[     0.004] I: Could not load the Qt platform plugin "xcb" in "/home/mati/.local/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
[     0.004] F: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

### Reproduce

I tried uninstall / reinstall but the response is the same.

### Expected behavior

For the default text editor program (notepad next in this case) to be automatically opened with the .yaml file used in the configuration entry (config.yaml or the applicable file used in the entry.

### Open Interpreter version

0.2.0

### Python version

3.10.12

### Operating System name and version

Pop!_OS 22.04 LTS

### Additional context

can´t think of anythin else that would help. It just didn´t launch the editor with the yaml files ready to be edited and now I need to open them manually. Thank you for your help!

**Comment by Notnaton** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/8c649d82-6a65-4fa6-b04c-8ebcceca9a89)
I piped the error into chatGPT
I don't know if this will fix it or even if it works, I don't use linux
If this looks ok, you can try it

**Comment by MatiasBarboza** [comment]
Hi @Notnaton, appreciate your response. I actually could have done that and it didn´t occur at the time, so thank you for that. By now you may have guessed I'm not a developer, just an enthusiast with very limited skills :)

I tried with your response but did not succed. I tried a bit more with bard to no avail. A google search led me to think that the problem relates to more than one python version being installed, but also didn't want to mess up my system so while trying to find an alternative, I got to know about Anaconda , so now I'm using OI in a dedicated environment and all is working fine now.

Hope this helps anyone else facing the same problem.

Thank you!
