### ISSUE TITLE
Content size exceeds 20 MB

### ISSUE THREAD

**Issue by commandodev** [OpenInterpreter/open-interpreter#926]
### Describe the bug

I have two monitors. One 4k and one samsung G9 (5120x1440).

I'm getting:

```
convert_to_openai_messages.py", line 138, in convert_to_openai_messages
    assert content_size_mb < 20, "Content size exceeds 20 MB"
AssertionError: Content size exceeds 20 MB
```

I assume this is because my screen image to too big?

### Reproduce

Probably only repos on large screens...

### Expected behavior

I not sure I expect anything different, perhaps a message telling my how big the image is. Or in multi screen set ups an option to only screen shot the active screen?

### Open Interpreter version

Open Interpreter 0.2.0 New Computer

### Python version

Python 3.10.12

### Operating System name and version

PopOS

**Comment by Arrendy** [comment]
Hi @commandodev 

I experienced the same error. I ended up changing my background image to be more basic to reduce screenshot file size as a workaround but this is only a bandaid. OI is investigating options for compressing screenshots while maintaining functionality. Will keep you posted!
