### ISSUE TITLE
Using interpreter --os --local causes the output to flip out

### ISSUE THREAD

**Issue by Onceisenoughyo** [OpenInterpreter/open-interpreter#959]
### Describe the bug

I've tried this multiple times and Mike from the discord server has told me to create an issue report. When I try to enable OS mode by using interpret --os --local and using obsidian-q6.gguf with LM Studio, my output keeps repeating the same few words or phrases.
![image](https://github.com/KillianLucas/open-interpreter/assets/157443633/a8e132a0-a0c1-438d-92d5-78897bc83f86)
This will continue until I kill the process by using ctrl-c. I'm on a windows laptop and here's my output from doing %info 
Python Version: 3.11.7
        Pip Version: 23.3.2
        Open-interpreter Version: cmd:Interpreter, pkg: 0.2.0
        OS Version and Architecture: Windows-10-10.0.22631-SP0
        CPU Info: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
        RAM Info: 15.62 GB, used: 11.92, free: 3.69

        # Interpreter Info

        Vision: True
        Model: gpt-4-vision-preview
        Function calling: False
        Context window: 110000
        Max tokens: 4096

        Auto run: True
        API base: None
        Offline: True

        Curl output: Not local

        # Messages

### Reproduce

Open LM Studio
Enable local server for obsidian-q6.gguf
Open Powershell
Type interpreter --os --local
Allow OS mode to enable
Type anything (I typed "Open a new edge tab")
Receive broken output

### Expected behavior

OS mode should enable and do what you'd want. For me, it would open a tab in Microsoft Edge

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/157443633/38b3f182-490b-4922-85b9-54354d790f3a)
![image](https://github.com/KillianLucas/open-interpreter/assets/157443633/7d39cc27-1471-465c-989c-ac8b21e1977e)

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows 11

### Additional context

I don't think this laptop has a dedicated GPU. Could that be part of the problem? LM Studio works fine in normal interpreter --local mode

**Comment by Arrendy** [comment]
I believe the issue is with the model being used. It may be more sensitive to the lack of meta tags. I will download it to verify, but I cannot replicate this issue using Mixtral. @Onceisenoughyo you mentioned that there is no dedicated GPU so I don't know if you can try with other models but if you can, comparing functionality between models would be helpful
